config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/dom_train'
  get 'static_pages/dom_ex_1'
  get 'static_pages/dom_ex_2'
  
  get 'static_pages/extra_notes'

  get 'static_pages/event_train'
  get 'static_pages/event_ex_1'
  get 'static_pages/event_ex_2'

  get 'static_pages/js_30_02'

  root to: "static_pages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def dom_train
  end

  def dom_ex_1
  end

  def dom_ex_2
  end

  def event_train
  end

  def event_ex_1
  end

  def event_ex_2
  end
  def extra_notes
  end

  def js_30_02
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestJs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/dom_ex_1.html.erb
<h1> Exercices sur le DOM </h1>

<h2>1. Introduction</h2>
<p>En liant un fichier HTML à un fichier JavaScript, tu vas permettre à ce dernier d'accéder au contenu de la page que tu es en train de coder. Et l'interface qui permet au fichier <code>.js</code> de faire ça s'appelle le Document Object Model ou DOM. Ce DOM est, en définitive, le standard du web pour accéder au contenu HTML d'un fichier.</p>
<p>Et évidemment, qui dit "accéder" dit "modifier" ... 🥳</p>

<h2>2. Historique et contexte</h2>
<p class="compte-moi">Maintenant que tu as repris JavaScript en écrivant à nouveau des boucles et des fonctions dans sa syntaxe, on va voir la principale utilisation de ce langage dans le web : manipuler à sa guise les pages HTML. Comme on te l'expliquait, Javascript est le standard, sur Internet, pour animer des pages web : faire apparaître/disparaître des éléments, changer le CSS, modifier le contenu d'éléments HTML, etc.</p>
<p>Pour bien te laisser le temps de maîtriser le DOM, on ne va pas parler encore d'évènements (= réagir aux actions de l'utilisateur : clic, appui sur une touche, passage de la souris sur un élément de la page, etc.). Aujourd'hui, on se contente d'apprendre une chose : accéder, via le DOM, aux éléments d'une page HTML et les modifier. Let's GO ! 🌠 </p>


<h2>3. La ressource</h2>
<p>Internet regorge de belles ressources sur le DOM et son fonctionnement. On va t'en proposer quelques-unes.</p>

<h3>3.1. Le principe général de fonctionnement du DOM</h3>
<p>Commence par regarder <a href="https://www.youtube.com/watch?v=eY_dlL4iAto" target="_blank">cette courte vidéo</a> qui te présente le principe général d'utilisation du DOM en JS.</p>
<p>Ensuite jette un oeil à <a href="https://youtu.be/iR01DKCgaH8" target="_blank">cette vidéo de la Khan Academy</a>.</p>
<p>Grâce à ces deux ressources, tu comprends bien qu'il y a 2 étapes quand on veut modifier un élément HTML :</p>
<ol>
  <li><b>Le cibler via un selecteur du DOM et le "stocker" dans une variable JS</b>. <br>
  Par exemple : <code>let elementsToBeModified = document.getElementsByTagName('p')</code> pour récupérer tous les éléments paragraphe (tag HTML <code>&lt;p></code>). <code>elementsToBeModified</code> contiendra plusieurs éléments du DOM, un peu comme un array.</li>
  <li class="compte-moi"><b>Passer ensuite une méthode du DOM sur la variable JS pour modifier l'élément qu'elle identifie</b>. <br>
  Par exemple : <code>elementsToBeModified[0].innerHTML = "coucou"</code> pour modifier le contenu HTML du premier élément <code>&lt;p></code> stocké dans <code>elementsToBeModified</code>.</li>
</ol>
<p>Voyons ces deux étapes plus en détail.</p>

<h3>3.2. Sélectionner un élément de la page HTML via le DOM</h3>
<p>Il existe plusieurs sélecteurs pour pointer vers les éléments d'une page HTML : </p>
<ul>
  <li>Lis ce <a href="https://openclassrooms.com/fr/courses/3306901-creez-des-pages-web-interactives-avec-javascript/3501871-decouvrez-le-dom" target="_blank">cours d'OpenClassRooms</a> qui te présente les généralités sur le DOM et les sélecteurs (pas besoin de faire les exercices après le "En résumé").</li>
  <li class="compte-moi">Maintenant passe au <a href="https://www.w3schools.com/js/js_htmldom_elements.asp" target="_blank">tuto W3schools sur les sélecteurs</a>. Il te présente différentes façons de pointer vers un élément <b>précis</b> de ta page.</li>
  <li>Ensuite, <a href="https://www.w3schools.com/js/js_htmldom_navigation.asp" target="_blank">ce tuto W3Schools</a> te montre une autre façon de pointer vers les éléments d'une page : en parcourant le DOM comme une arborescence de noeuds.</li>
  <li>Retour sur <a href="https://openclassrooms.com/fr/courses/3306901-creez-des-pages-web-interactives-avec-javascript/3501886-parcourez-le-dom" target="_blank">le tuto OpenClassRoom</a> pour avoir plus de détails par sélecteur en t'arrêtant avant la partie "Obtenir des informations sur les éléments".</li>
</ul>

<h3>3.3. Modifier les éléments de la page HTML</h3>
<p class="compte-moi">Une fois un élément ciblé, tu peux modifier de plusieurs façons la page :</p>
<ul>
  <li>Soit en modifiant l'élément lui-même (en changeant son code HTML ou ses attributs comme <code>src</code> ou <code>href</code>) comme <a href="https://www.w3schools.com/js/js_htmldom_html.asp" target="_blank">expliqué ici</a>.</li>
  <li>Soit en changeant son CSS <a href="https://www.w3schools.com/js/js_htmldom_css.asp" target="_blank">comme expliqué là</a> (inutile de lire la partie concernant les évènements : on en parlera plus tard).</li>
  <li>Soit tu peux carrément créer, supprimer ou remplacer des nouveaux "noeuds" du DOM <a href="https://www.w3schools.com/js/js_htmldom_nodes.asp" target="_blank">comme le montre W3schools ici</a>.</li>
</ul>
<p>Ce <a href="https://openclassrooms.com/fr/courses/3306901-creez-des-pages-web-interactives-avec-javascript/3501891-modifiez-la-structure-de-la-page" target="_blank">cours OpenClassRooms</a> résume pas mal toutes les modifications que tu peux apporter (inutile de faire les exercices à la fin).</p>

<h2 class="compte-moi">3.4. Pour finir ...</h2>
<p>Cette <a href="https://www.youtube.com/watch?v=1N5cNqL6PjI&feature=youtu.be" target="_blank">vidéo de la Khan Academy</a> montre un exemple complet de manipulation du DOM : on sélectionne puis on modifie !</p>
<p class="compte-moi">Dernier point important à avoir en tête : la majorité des sélecteurs du DOM vont te retourner des éléments HTML ou des Noeuds sous une forme proche d'un array mais <b>sans qu'il s'agisse réellement d'array</b>. W3Schools explique cela très bien dans les cours suivants (notamment en fin de page) :  </p>
<ul>
  <li class="compte-moi"><a href="https://www.w3schools.com/js/js_htmldom_collections.asp" target="_blank">Ici ils parlent des collections HTML</a> retournées notamment par les sélecteurs comme <code>getElementsByTagName</code> ou <code>getElementsByClassName</code> (ce qui explique le <b>"s"</b> à "Elements").</li>
  <li><a href="https://www.w3schools.com/js/js_htmldom_nodelist.asp" target="_blank">Ici ils parlent des collections de Noeuds</a> retournées notamment par le sélecteur <code>querySelectorAll</code>.</li>
</ul>

<h2>4. Points importants à retenir</h2>
<div>
  <p id="coucou">Le DOM est une interface standardisée pour accéder au contenu HTML d'une page.</p>
  <h3>4.1. Pour parcourir le DOM</h3>
  <p>Voici comment sélectionner, via le DOM, un élément HTML ou un groupe d'éléments HTML de ton choix :</p>
  <ul>
    <li class="compte-moi">via son Id CSS : <code>document.getElementById("tableau")</code></li>
    <li>via leur tag HTML (ex : &lt;h1>, &lt;p> ou encore &lt;a>) : <code>document.getElementsByTagName("div")</code></li>
    <li>via leur classe CSS : <code>document.getElementsByClassName("title")</code> </li>
    <li class="compte-moi">via une requête type CSS (mélangeant tags et class par exemple) : <code>document.querySelectorAll("p.title")</code></li>
  </ul>

  <p>Une fois un élément sélectionné, on peut naviguer dans le DOM comme au sein d'une arborescence en passant entre noeuds "parents" et noeuds "enfants". Pour cela, les principales fonctions sont les suivantes (dans nos exemples, on les applique à un élément <code>elementFromDOM</code>) :</p>
  <ul>
    <li style="color: white; font-size: 0.01em;">Bien joué, tu as trouvé ce noeud "caché" :)</li>
    <li>Pour remonter au noeud parent, on fait : <code>elementFromDOM.parentNode</code></li>
    <li>Pour aller au 3ème noeud enfant, on fait : <code>elementFromDOM.childNodes[2]</code></li>
    <li>Pour remonter au dernier noeud enfant, on fait : <code>elementFromDOM.lastChild</code></li>
    <li>Pour passer au prochain "noeud" ayant le même parent, on fait : <code>elementFromDOM.nextSibling</code></li>
    <li>Pour passer au "noeud" précédent ayant le même parent, on fait : <code>elementFromDOM.previousSibling</code></li>
  </ul>
</div>

<h3>4.2. Pour modifier le DOM</h3>

<p>Voici quelques exemples d'actions que l'on peut effectuer sur un élément du DOM (exemples en imaginant que l'élément est stocké avec la variable <code>elementFromDOM</code>: </p>
<ul>
  <li>Changer le contenu HTML avec <code>elementFromDOM.innerHTML = "nouvelle valeur"</code>.</li>
  <li class="compte-moi">Changer le texte avec <code>elementFromDOM.textContent = "nouvelle valeur"</code>.</li>
  <li>Ajouter ou supprimer une classe CSS avec <code>elementFromDOM.classList.add("title")</code> ou <code>elementFromDOM.classList.remove("title")</code>.</li>
  <li>Changer un attribut avec <code>elementFromDOM.setAttribute("href", "http://www.thehackingproject.org")</code>.</li>
  <li>Modifier une propriété CSS avec <code>elementFromDOM.style.font = "nouvelle propriete"</code>, par exemple <code>elementFromDOM.style.color = "red"</code>.</li>
</ul>

<p class="compte-moi">Et pour finir voici les principales actions que l'on peut effectuer pour modifier la structure de la page HTML :</p>
<ul>
  <li>Créer un élément HTML avec <code>document.createElement(element)</code></li>
  <li>Supprimer un élément HTML avec <code>document.removeChild(element)</code> ou <code>elementFromDOM.remove()</code></li>
  <li>Rajouter un élément HTML avec<code>document.appendChild(element)</code></li>
  <li>Remplacer un élément HTML avec <code>document.replaceChild(element)</code></li>
</ul>

<h2 class="compte-moi">5. Pour aller plus loin</h2>
<p>Tu trouveras une liste assez complète des fonctions disponibles via le DOM dans la <a href="https://developer.mozilla.org/fr/docs/Web/API/Document" target="_blank">documentation de Mozilla</a>.</p>

<%= javascript_pack_tag 'dom_ex_1'%>

app/views/static_pages/dom_train.html.erb
<h1> Entrainement </h1>

<div id="fromage">Hello</div>
<div id="vin">Bye</div>

<div class="roger">Loremmm</div>

<div class="naruto">Narutoo1</div>
<div class="naruto">Narutoo2</div>
<div class="naruto">Narutoo3</div>
<div class="naruto">Narutoo4</div>


<%= javascript_pack_tag 'dom_train'%>

app/views/static_pages/entrainement.html.erb
<h1> Entrainement </h1>

<div id="fromage">Hello</div>
<div id="vin">Bye</div>

<div class="roger">Loremmm</div>

<div class="naruto">Narutoo1</div>
<div class="naruto">Narutoo2</div>
<div class="naruto">Narutoo3</div>
<div class="naruto">Narutoo4</div>


<%= javascript_pack_tag 'entrainement-DOM'%>

app/views/static_pages/event_ex_1.html.erb
<h1> Exercices EVENT </h1>
<hr>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">Coucou !</h4>
            <p class="text-muted">Et oui, depuis le début j'étais caché. Merci de m'avoir libéré</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              <li><a href="#" class="text-white">Follow on Twitter</a></li>
              <li><a href="#" class="text-white">Like on Facebook</a></li>
              <li><a href="#" class="text-white">Email me</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="navbar navbar-dark bg-dark box-shadow">
      <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
          <strong>JS & Events</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

  <main role="main">
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Bienvenue</h1>
        <p>
          <a href="http://www.thehackingproject.org" class="btn btn-primary my-2"><==</a>
          <a href="#" class="btn btn-secondary my-2">==></a>
        </p>
      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Card image cap" src="https://img.icons8.com/color/480/000000/html-5.png">
              <div class="card-body">
                <p class="card-text">L’HyperText Markup Language, généralement abrégé HTML, est le langage de balisage conçu pour représenter les pages web</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-success">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Card image cap" src="https://img.icons8.com/color/480/000000/css3.png">
              <div class="card-body">
                <p class="card-text">Les feuilles de style en cascade, généralement appelées CSS de l'anglais Cascading Style Sheets, forment un langage informatique qui décrit la présentation des documents HTML et XML</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-success">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Card image cap" src="https://img.icons8.com/color/480/000000/javascript.png">
              <div class="card-body">
                <p class="card-text">JavaScript est un langage de programmation de scripts principalement employé dans les pages web interactives mais aussi pour les serveurs. C'est un langage orienté objet à prototype.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-success">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Card image cap" src="https://img.icons8.com/color/480/000000/ruby-programming-language.png">
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-success">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Card image cap" src="https://img.icons8.com/color/480/000000/bootstrap.png">
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-success">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Card image cap" src="https://img.icons8.com/color/480/000000/github.png">
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-success">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </main>

  <footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <a href="#">Back to top</a>
      </p>
      <p>Album example is © Bootstrap, but please download and customize it for yourself!</p>
      <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
    </div>
  </footer>

  <script src="script.js"></script>

<hr>

<%= javascript_pack_tag 'event_ex_1'%>

app/views/static_pages/event_ex_2.html.erb
<h1><center> Drum kit </center></h1>
<div class="boxes-container" id="log">
<div class="row">
  <div class="col">
    <div class="box">
      <div class="box-title">A</div>
      <div class="box-content">kick</div>
      <audio id="sound" >
        <source src="http://soundcavern.free.fr/kick/kick010.wav" >
      </audio>
    </div>
  </div>
  <div class="col">
    <div class="box">
      <div class="box-title">Z</div>
      <div class="box-content">head</div>
      <audio id="sound" >
        <source src="http://www.denhaku.com/r_box/sr16/sr16bd/headpnch.wav" >
      </audio>
    </div>
  </div>
  <div class="col">
    <div class="box">
      <div class="box-title">E</div>
      <div class="box-content">foot</div>
      <audio id="sound" >
        <source src="http://www.denhaku.com/r_box/sr16/sr16bd/hi%20foot.wav" >
      </audio>
    </div>
  </div>
  <div class="col">
    <div class="box">
      <div class="box-title">R</div>
      <div class="box-content">beat</div>
      <audio id="sound" >
        <source src="http://patrickjohnston.org/ASM/ROM%20data/Super%20Metroid/BF%20stuff/Aveon%20Theme/3_beat.wav" >
      </audio>
    </div>
  </div>
  <div class="col">
    <div class="box">
      <div class="box-title">T</div>
      <div class="box-content">hall</div>
      <audio id="sound" >
        <source src="http://www.denhaku.com/r_box/sr16/sr16bd/brt%20hall.wav" >
      </audio>
    </div>
  </div>
  <div class="col">
    <div class="box">
      <div class="box-title">Y</div>
      <div class="box-content">stab</div>
      <audio id="sound" >
        <source src="http://www.denhaku.com/r_box/sr16/sr16bd/lo%20stab.wav" >
      </audio>
    </div>
  </div>
  <div class="col">
    <div class="box">
      <div class="box-title" name="QQQQ">Q</div>
      <div class="box-content">honst</div>
      <audio id="sound" >
        <source src="http://www.denhaku.com/r_box/sr16/sr16bd/lo%20honst.wav" >
      </audio>
    </div>
  </div>
  <div class="col">
    <div class="box">
      <div class="box-title">S</div>
      <div class="box-content">punch</div>
      <audio id="sound" >
        <source src="http://www.denhaku.com/r_box/sr16/sr16bd/punch%20rm.wav" >
      </audio>
    </div>
  </div>
</div>
</div>



<%= javascript_pack_tag 'event_ex_2'%>

app/views/static_pages/event_train.html.erb
<br><br>

<! --- onclick method --->
  <h1>onclick menu</h1>
  <button class="hamburger">Menu 2</button>
  <div class="list-hamburger">
    <ul>
      <li><a href="#">lien 1</a></li>
      <li><a href="#">lien 2</a></li>
      <li><a href="#">lien 3</a></li>
      <li><a href="#">lien 4</a></li>
    </ul>
  </div>

  <! --- addEventListener method --->
  <hr>
  <h1>addEventListener</h1>
  <h3 id="gros titre">Les évènements</h3>
  <p class="click-1"> Cliquez moi ! ( add eventListener simple ) </p>
  <p class="click-2"> Cliquez moi ! ( add eventListener fonction anonyme ) </p>
  <p class="click-3"> Cliquez moi ! ( add eventListener multi event ) </p>
  <p class='mouse-1'> Passez sur moi ! </p>

  <! --- l'objet event --->
  <hr>
  <h1>objet event</h1>
  <div id="div1">
    <p id="p1"> Qui est le déclencheur ? Le porteur d'évènements ?</p>
 
  </div>
  <p class="object-event-1"> Qui est le déclencheur ? Le porteur d'évènements ?</p>
  <p class="object-event-2"> Qui est le déclencheur ? Le porteur d'évènements ?</p>
  <p class="object-event-3"> Qui est le type d'évènement ?</p>

  <div id="div2">
    <p id="p2"> La propagation .. </p>
 
  </div>

  <div id="div3">
  <p id="p3"> Event prevault ..  </p>

</div>


  <%= javascript_pack_tag 'event_train'%>


  <hr>

app/views/static_pages/extra_notes.html.erb
<%= javascript_pack_tag 'extra_notes'%>

app/views/static_pages/index.html.erb
<h1>JS entrainement/exercices</h1>

<div class="card-deck">

<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Entrainement autour du DOM</h5>
    <p class="card-text">Résultats dans la console, et commentaires dans le fichier JS <i>app/javascript/packs/entrainement.js</p>
    <%= button_to 'train-DOM', static_pages_dom_train_path, method: :get %>
  </div>
</div>

<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Exercice DOM 1</h5>
    <p class="card-text"> Entrainement dans la console, niveau débutant <i>app/javascript/packs/exercice1.js</p>
    <%= button_to 'Exercice 1', static_pages_dom_ex_1_path, method: :get  %>
  </div>
</div>

<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Exercice DOM 2</h5>
    <p class="card-text">Changement des évènements du DOM, et itérations sur les changements <i>app/javascript/packs/exercice2.js</p>
    <%= button_to 'Exercice 2', static_pages_dom_ex_2_path, method: :get  %>
  </div>
</div>


<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Train event</h5>
    <p class="card-text"> </p>
    <%= button_to 'exo event 1', static_pages_event_train_path, method: :get  %>
  </div>
</div>

<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Ajax train</h5>
    <p class="card-text"> </p>
    <%= button_to 'ajax train', static_pages_extra_notes_path, method: :get  %>
  </div>
</div>

<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Exercice event 1</h5>
    <p class="card-text"> </p>
    <%= button_to 'exo event 1', static_pages_event_ex_1_path, method: :get  %>
  </div>
</div>

<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">JS_30 #01</h5>
    <p class="card-text"> </p>
    <%= button_to 'JS_30_01', static_pages_event_ex_2_path, method: :get  %>
  </div>
</div>

<div class="card card-custom" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">JS_30 #02</h5>
    <p class="card-text"> </p>
    <%= button_to 'JS_30_02', static_pages_js_30_02_path, method: :get  %>
  </div>
</div>

</div>

app/views/static_pages/js_30_02.html.erb
<%= javascript_pack_tag 'js_30_02'%>